

--DDL
CREATE
ALTER
DROP

CREATE DATABASE AulaAtos;
DROP DATABASE AulaAtos;

CREATE TABLE ALUNOS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	IDADE INTEGER
);

--PRIMARY KEY - chave primaria
--NULL e NOT NULL - campo nulo ou não nulo
--IDENTITY - auto incremento

DROP TABLE ALUNOS; -- exclui a tabela

ALTER TABLE ALUNOS 
ADD RG VARCHAR(12);

ALTER TABLE ALUNOS
DROP COLUMN IDADE;

ALTER TABLE ALUNOS 
ALTER COLUMN NOME VARCHAR(200) NOT NULL;

sp_rename 'ALUNOS.NOME', 'nome_completo', 'COLUMN';--RENOMEAR COLUNA

------------------------

CREATE TABLE CURSOS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CARGA_HORARIA INTEGER NOT NULL,
	ATIVO BIT DEFAULT 1,
	DESCRICAO TEXT
)

CREATE TABLE DISCIPLINAS 
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CARGA_HORARIA INTEGER NOT NULL,
	FK_CURSO INTEGER NOT NULL,
	FOREIGN KEY (FK_CURSO) REFERENCES CURSOS(ID)
)

CREATE TABLE MATRICULAS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	FK_ALUNO INTEGER NOT NULL,
	FK_CURSO INTEGER NOT NULL,
	FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS(ID),
	FOREIGN KEY(FK_CURSO) REFERENCES CURSOS(ID)
)


------------------------

--DML
INSERT
UPDATE
DELETE
SELECT

--CRUD = CreateReadUpdateDelete

SELECT * FROM alunos -- selecionar

--INSERT

INSERT INTO alunos 
VALUES ('Fabrício', '544684', 32);

INSERT INTO alunos (NOME, CPF)
VALUES ('Murilo', '545646546');

---UPDATE
UPDATE ALUNOS 
SET IDADE = 27
WHERE ID = 2

UPDATE ALUNOS 
SET IDADE = 22
WHERE NOME = 'Fabrício'

UPDATE ALUNOS 
SET IDADE = 32, CPF = '5464684'
WHERE ID = 5

UPDATE ALUNOS 
SET CPF = '111111111'
WHERE NOME = 'Fabrício' and idade > 25

UPDATE ALUNOS
SET NOME = NULL
WHERE ID = 12

UPDATE ALUNOS
SET NOME = ''
WHERE ID = 14

UPDATE ALUNOS
SET IDADE = NULL
WHERE ID = 12

--DELETE

DELETE FROM ALUNOS

DELETE FROM ALUNOS
WHERE ID = 11

DELETE FROM ALUNOS
WHERE IDADE IS NULL

DELETE FROM ALUNOS
WHERE IDADE IS NOT NULL

DELETE FROM ALUNOS 
WHERE NOME = 'fabrício'

SELECT * FROM alunos
where nome != ''
order by nome

SELECT * FROM alunos
where nome != ''
order by nome ASC

SELECT * FROM alunos
where nome != ''
order by 2 DESC
